<?php

namespace CarbuBundle\Repository;

/**
 * MileageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MileageRepository extends \Doctrine\ORM\EntityRepository
{
}
