services:
  optimus.obfuscator:
    class: OptimusBundle\Service\Obfuscator
    autowire: false
    arguments:
      $prime: '%optimus_prime%'
      $inverted: '%optimus_inverse%'
      $random: '%optimus_random%'